name: flutter_rxstore
description: Contains a Flutter widget to easily obtain a reference to an rxstore
version: 0.3.0
homepage: https://github.com/johanflint/rxstore.dart

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  rxdart: ">=0.26.0 <0.27.0"
  rxstore: ">=0.3.0 <1.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
