# Defines a default set of lint rules enforced for
# projects at Google. For details and rationale,
# see https://github.com/dart-lang/pedantic#enabled-lints.
include: package:pedantic/analysis_options.yaml

analyzer:
  strong-mode:
    implicit-dynamic: false
  errors:
    dead_code: error
    unused_import: error
    unused_local_variable: error
    missing_required_param: warning
    missing_return: warning

linter:
  rules:
    # Keep these in the same order as the Dart Lint rules page to make maintenance easier
    # https://github.com/dart-lang/linter/blob/master/example/all.yaml
    - avoid_bool_literals_in_conditional_expressions
    - avoid_catching_errors
    - avoid_equals_and_hash_code_on_mutable_classes
    - avoid_returning_null_for_void
    - avoid_returning_this
    - avoid_unnecessary_containers
    - avoid_unused_constructor_parameters
    - await_only_futures
    - camel_case_types
    - cascade_invocations
    - comment_references
    - constant_identifier_names
    - diagnostic_describe_all_properties
    - directives_ordering
    - empty_statements
    - file_names
    - hash_and_equals
    - implementation_imports
    - iterable_contains_unrelated_type
    # - lines_longer_than_80_chars # readability is sometimes better with longer lines
    - list_remove_unrelated_type
    - non_constant_identifier_names
    - overridden_fields
    - package_names
    - package_prefixed_library_names
    - parameter_assignments
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - prefer_constructors_over_static_methods
    - prefer_final_in_for_each
    - prefer_final_locals
    - prefer_foreach
    - prefer_function_declarations_over_variables
    - prefer_if_elements_to_conditional_expressions
    - prefer_initializing_formals
    - prefer_inlined_adds
    - prefer_interpolation_to_compose_strings
    - prefer_is_not_operator
    - prefer_null_aware_operators
    - prefer_typing_uninitialized_variables
    - provide_deprecation_message
    - sort_pub_dependencies
    - sort_unnamed_constructors_first
    - test_types_in_equals
    - throw_in_finally
    - unnecessary_await_in_return
    - unnecessary_brace_in_string_interps
    - unnecessary_getters_setters
    - unnecessary_null_aware_assignments
    - unnecessary_overrides
    - unnecessary_parenthesis
    - unnecessary_statements
    - use_string_buffers
    - void_checks
