name: rxstore
description: Stream-based Redux implementation with support for side-effects.
version: 0.1.0
author: Johan Flint <johan.flint@gmail.com>
homepage: https://github.com/johanflint/rxstore.dart

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  rxdart: ^0.20.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.9.0
