name: rxstore
description: Stream-based Redux implementation with support for side-effects.
version: 0.2.1
homepage: https://github.com/johanflint/rxstore.dart

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  rxdart: ">=0.26.0 <0.27.0"

dev_dependencies:
  meta: ^1.3.0
  pedantic: ^1.11.0
  test: ^1.16.0
